options:
  # Mode can be "nearest", "furthest" or "all".
  # "nearest" will show the nearest events, "furthest" will show the furthest
  # events. The number of events are shown is determined by the
  # future_events_count and past_events_count options.
  list_mode: nearest

  # When the mode is "all", the future_events_count and past_events_count
  # options are ignored.
  list_future_events_count: 5
  list_past_events_count: 5

event_lists:
  otaku_events: ~/playground/events/otaku.events

  test_events: ~/playground/events/test.events
